version: '3'
services:
  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .dev.env
    environment:
    - DJANGO_SETTINGS_MODULE=settings
    - POSTGRES_HOST=db
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: npm run start
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: postgres:14-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=story
      - POSTGRES_PASSWORD=password
    ports:
      - "5435:5432"
    restart: always


volumes:
  postgres_data:
  node_modules:
