# Generated by Django 4.2.3 on 2023-07-31 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=124)),
                ('body', models.TextField()),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='newsletters.newsletter')),
                ('recipients', models.ManyToManyField(related_name='emails', to='newsletters.recipient')),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
    ]
